### ISSUE TITLE
awesome Project! some suggest!

### ISSUE THREAD

**Issue by gybin02** [mipegir/RemoteLogcatLibrary#1]
1. THIS LogCat UI Is better；
https://github.com/trainto/Catalogger
2.  need auto scroll.

**Comment by mipegir** [comment]
Thank you by test it!
The UI can be improved, but autoscroll runs by default.  It does not work?

**Comment by gybin02** [comment]
My bad , scroll can work

**Comment by mipegir** [comment]
Thanks for informing! I close this issue!
